require 'bare_gato/winning_strategies/row'
require 'bare_gato/winning_strategies/column'
require 'bare_gato/winning_strategies/diagonal'
require 'bare_gato/winning_strategies/inverse_diagonal'
require 'bare_gato/move'
require 'bare_gato/game'
